version: '3.1'

services:
  appliances:
    build: ./appliances
    container_name: appliances
    ports:
      - 8081:4000
    expose:
      - 8081
    volumes:
      - ./appliances/src:/home/app/src
    command: npm start
  auth:
    build: ./auth
    container_name: auth
    ports:
      - 8082:4001
    expose:
      - 8082
    volumes:
      - ./auth/src:/home/app/src
    command: npm start

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 4000:4000
    links:
      - appliances
      - auth
